### ISSUE TITLE
Errors when building initial set of collections

### ISSUE THREAD

**Issue by alistair-low** [nknaian/albumcollections#2]
Hello, this looks like a really useful tool and I can't wait to start using it!

Unfortunately, I get errors like the following after logging in with my Spotify account:
`Failed to load user collections - http status: 404, code:-1 - https://api.spotify.com/v1/playlists/2o7ZYZcArT0ceKFlQ1ToPX/tracks?limit=100&offset=0&additional_types=track: Not found., reason: None `

It looks like this only happens on private playlists, but I'm not sure whether those are meant to be supported or not.

Steps to Reproduce:
1. Create a private playlist and add some items
2. Log in to the web app with your Spotify account

Possible Solutions:
* If private playlists should be supported, add the playlist-read-private scope?
* If not, add a check that the playlist is public before appending it to the list on https://github.com/nknaian/albumcollections/blob/main/albumcollections/spotify/spotify_user_interface.py#L105

**Comment by nknaian** [comment]
@alistair-low thanks for the detailed assessment, I'm excited that you want to get the app working for you! This app is still really in it's infancy in terms of robust support so I appreciate the comment.

I think those are both reasonable solutions, I honestly don't see a reason why not to support private playlists so I think I'll go ahead and add that scope. I don't think I have any private playlists in my account, this why I never crossed this problem before.

Also I'm almost done with a bit of an overhaul set of changes, one of which should still allow some playlists to load even when there's issues to load others (because I've realized there are 
probably tons of weird edge cases that I won't be able to handle right off the bat!).

**Comment by nknaian** [comment]
This should now be fixed with https://github.com/nknaian/albumcollections/commit/5d4026bcb2dda8b185584e0acb41c73108c0165d, I've deployed to the website and private playlists are getting loaded and played for me. Turned out there was another problem in addition to the private scope missing...I needed to use the user 'OAuth' api interface when doing any playlist interaction as well

@alistair-low let me know if this works for you now and then I'll close the issue!

**Comment by alistair-low** [comment]
It works! Thanks a lot!
I get sporadic "Unexpected failure occurred" error messages but they don't break anything so I can ignore them.

**Comment by nknaian** [comment]
Oh interesting...well feel free to raise another issue if you figure out why that's happening and I'll keep my eye out...
